import { defineConfig } from 'vite';
import { resolve } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = resolve(__filename, '..');

export default defineConfig({
  root: 'public',
  base: './',
  build: {
    outDir: resolve(__dirname, 'build/electron'),
    emptyOutDir: true,
    minify: false,
    sourcemap: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'public/main.js'),
        preload: resolve(__dirname, 'public/preload.js'),
      },
      output: {
        entryFileNames: '[name].cjs',
        chunkFileNames: '[name].cjs',
        assetFileNames: '[name].[ext]',
        format: 'cjs',
        exports: 'auto',
      },
      external: [
        'electron',
        'fs',
        'path',
        'crypto',
        'os',
        'child_process',
        'http',
        'https',
        'stream',
        'util',
        'url',
        'zlib',
        'events',
        'buffer',
        'assert',
        'tty',
        'net',
        'tls',
        'dns',
        'dgram',
        'module',
        'constants',
        'querystring',
        'string_decoder',
        'timers',
        'worker_threads',
        'perf_hooks',
        'async_hooks',
        'v8',
        'vm',
        'wasi',
        'inspector',
        'repl',
        'readline',
        'trace_events',
        'diagnostics_channel',
        'process',
        'perf_hooks',
        'assert/strict',
        'node:fs',
        'node:path',
        'node:crypto',
        'node:os',
        'node:child_process',
        'node:http',
        'node:https',
        'node:stream',
        'node:util',
        'node:url',
        'node:zlib',
        'node:events',
        'node:buffer',
        'node:assert',
        'node:tty',
        'node:net',
        'node:tls',
        'node:dns',
        'node:dgram',
        'node:module',
        'node:constants',
        'node:querystring',
        'node:string_decoder',
        'node:timers',
        'node:worker_threads',
        'node:perf_hooks',
        'node:async_hooks',
        'node:v8',
        'node:vm',
        'node:wasi',
        'node:inspector',
        'node:repl',
        'node:readline',
        'node:trace_events',
        'node:diagnostics_channel',
        'node:process',
        'node:assert/strict',
      ],
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
    extensions: ['.js', '.json', '.node'],
  },
  optimizeDeps: {
    exclude: ['electron'],
  },
  define: {
    // Don't define NODE_ENV so it can be set at runtime
    'process.platform': JSON.stringify(process.platform),
    'process.arch': JSON.stringify(process.arch),
  },
});
